patch:
  schema/name: å°é¹¤åŒæ‹¼
  switches:
    - name: ascii_mode
      reset: 0
      states: [ ä¸­æ–‡, è¥¿æ–‡ ]
    - name: emoji_suggestion
      reset: 1
      states: [ "No", "Yes" ]
    - name: full_shape
      states: [ åŠè§’, å…¨è§’ ]
    - name: simplification
      reset: 1
      states: [ æ¼¢å­—, æ±‰å­— ]
    - name: ascii_punct
      states: [ ã€‚ï¼Œ, ï¼ï¼Œ ]
  engine/translators:
    # - lua_translator@date_translator
    # - lua_translator@week_translator
    - punct_translator
    - script_translator
    - table_translator@custom_phrase
  engine/filters:
    - simplifier@emoji_suggestion
    - simplifier
    - uniquifier
    - charset_filter@gbk
    - single_char_filter
  engine/processors:
    - ascii_composer
    - recognizer
    - key_binder
    - speller
    - punctuator
    - selector
    - navigator
    - express_editor
  emoji_suggestion:
    opencc_config: emoji.json
    option_name: emoji_suggestion
    # tips: all
  reverse_lookup: {}
  
  #è¼‰å…¥æœ™æœˆæ‹¼éŸ³æ“´å……è©åº«
  'translator/dictionary': luna_pinyin.extended
  'translator/preedit_format': {}

  # è‡ªå®šä¹‰ç¬¦å·ä¸Šå±
  punctuator:
    import_preset: symbols
    symbols:
      "/bb": [ğŸ˜‚,ğŸ˜€,ğŸ˜,ğŸº,ğŸ˜ƒ,ğŸ˜„,ğŸ˜…,ğŸ˜†,ğŸ˜‰,ğŸ˜Š,ğŸ˜‹,ğŸ˜,ğŸ˜,ğŸ˜˜,ğŸ˜—]
      "/ss": [ğŸ’ª,ğŸ‘ˆ,ğŸ‘‰,ğŸ‘†,ğŸ‘‡,âœ‹,ğŸ‘Œ,ğŸ‘,ğŸ‘,âœŠ,ğŸ‘Š,ğŸ‘‹,ğŸ‘,ğŸ‘]
    half_shape:
      "#": "#"
      "*": "*"
      "`": "`"
      "~": "~"
      "@": "@"
      "=": "="
      '\': "ã€"
      "%": "%"
      "$": ["Â¥", "$", "â‚¬", "Â£", "Â¢", "Â¤"]
      "|": ["|", "ï½œ", "Â·", "ãƒ»", "Â§", "Â¦", "â€–", "ï¸´"]
      "/": ["/", "Ã·"]
      "'": { pair: ["ã€Œ", "ã€"] }
      "[": ["ã€", "ã€”", "ï¼»"]
      "]": ["ã€‘", "ã€•", "ï¼½"]
      "<": "ã€Š"
      ">": "ã€‹"

  recognizer/patterns/punct: "^/([0-9]0?|[A-Za-z]+)$"

  ### åŒæ‹¼ä½¿ç”¨è‡ªå®šä¹‰è¯å…¸ custom_phrase.txt
  custom_phrase:
    dictionary: ""
    user_dict: custom_phrase
    db_class: stabledb
    enable_completion: false
    enable_sentence: false
    initial_quality: 1
  "engine/translators/@5": table_translator@custom_phrase

  # æ¨¡ç³ŠéŸ³
  'speller/algebra':
    - erase/^xx$/
    - derive/^([jqxy])u$/$1v/
    - derive/^([aoe])([ioun])$/$1$1$2/
    - derive/([ie])ng$/$1n/ #  ing => in
    - derive/([ie])n$/$1ng/ # in => ing
    - xform/^([aoe])(ng)?$/$1$1$2/
    - xform/iu$/Q/
    - xform/(.)ei$/$1W/
    - xform/uan$/R/
    - xform/[uv]e$/T/
    - xform/un$/Y/
    - xform/^sh/U/
    - xform/^ch/I/
    - xform/^zh/V/
    - xform/uo$/O/
    - xform/ie$/P/
    - xform/i?ong$/S/
    - xform/ing$|uai$/K/
    - xform/(.)ai$/$1D/
    - xform/(.)en$/$1F/
    - xform/(.)eng$/$1G/
    - xform/[iu]ang$/L/
    - xform/(.)ang$/$1H/
    - xform/ian$/M/
    - xform/(.)an$/$1J/
    - xform/(.)ou$/$1Z/
    - xform/[iu]a$/X/
    - xform/iao$/N/
    - xform/(.)ao$/$1C/
    - xform/ui$/V/
    - xform/in$/B/
    - xlit/QWRTYUIOPSDFGHJKLZXCVBNM/qwrtyuiopsdfghjklzxcvbnm/


# Rx: BlindingDark/rime-easy-en:customize:schema=double_pinyin_flypy
  # __include: easy_en:/patch
  # easy_en/enable_sentence: false
# Rx: lotem/rime-octagram-data:customize:schema=luna_pinyin,model=hans
  #  __include: grammar:/hant
# Rx: BlindingDark/rime-lua-select-character:customize:schema=luna_pinyin
  # __include: lua_select_character:/patch # éœ€è¦lua_selectoræ‰“å¼€æœ¬è¡Œæ³¨é‡Š

